### ISSUE TITLE
[SUGGESTION] Give players temporary flight

### ISSUE THREAD

**Issue by Faun471** [Kubajsa/easyFlight#3]
The title is self explanatory.

This could be an optional command right after the `<player>` or `<on|off>` argument.

Examples:
`/efly everyone on 30m` (turns on flight for 30 minutes)
`/efly everyone off 30m` (turns off flight for 30 minutes)
`/fly <player> 30m` (turns on flight for 30 minutes)

**Comment by Kubajsa** [comment]
That's a great suggestion! I'll try to add that soon
